# Generated by Django 4.2.6 on 2023-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keibaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racedetail',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='racedetail',
            name='position',
        ),
        migrations.AddField(
            model_name='racedetail',
            name='horse_name',
            field=models.CharField(default='Unknown Horse', max_length=100),
        ),
        migrations.AddField(
            model_name='racedetail',
            name='jockey_name',
            field=models.CharField(default='Unknown Jockey', max_length=100),
        ),
        migrations.AddField(
            model_name='racedetail',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racedetail',
            name='odds',
            field=models.FloatField(default=0.0),
        ),
    ]
