# Generated by Django 4.2.6 on 2023-10-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('weather', models.CharField(max_length=50)),
                ('ground_status', models.CharField(max_length=50)),
                ('prize_distribution', models.TextField()),
                ('race_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jockey_name', models.CharField(max_length=200)),
                ('frame_number', models.IntegerField()),
                ('horse_number', models.IntegerField()),
                ('odds', models.FloatField()),
                ('weight', models.FloatField()),
                ('training_center', models.CharField(max_length=50)),
                ('previous_race_result', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('weight_carried', models.FloatField()),
                ('win_rate', models.FloatField()),
                ('top3_rate', models.FloatField()),
                ('trainer', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('breeder', models.CharField(max_length=200)),
                ('pedigree', models.TextField()),
                ('weight_change', models.FloatField()),
                ('popularity_rank', models.IntegerField()),
                ('days_since_last_race', models.IntegerField()),
                ('sire', models.CharField(max_length=200)),
                ('dam', models.CharField(max_length=200)),
                ('dams_sire', models.CharField(max_length=200)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.race')),
            ],
        ),
    ]
