# Generated by Django 4.2.6 on 2023-10-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
